#define PROBLEM "https://yukicoder.me/problems/no/1659"
#include <iostream>
#include "utils/macros.hpp"
#include "modulus/mint.hpp"
#include "number/primes.hpp"
#include "number/primes_extra.hpp"
#include "modulus/multichoose_simple.hpp"
using namespace std;

prepared_primes primes(1e6 + 100);

constexpr int64_t MOD = 1000000007;
mint<MOD> solve(int64_t n, int64_t k) {
    mint<MOD> ans = 1;
    for (auto [p, e] : list_prime_factors_as_map(primes, n)) {
        // ans *= multichoose_simple<MOD>(k, e);
        mint<MOD> y = 0;
        REP (x, e + 1) {
            y += multichoose_simple<MOD>(k, x);
        }
        ans *= y;
    }
    return ans;
}

// generated by oj-template v4.8.0 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N, K;
    std::cin >> N >> K;
    auto ans = solve(N, K);
    std::cout << ans << '\n';
    return 0;
}
